### ISSUE TITLE
cannot serve

### ISSUE THREAD

**Issue by yukopangestu** [mohdrashid/PaperAdmin#2]
Error message:
`ERROR in C:/xampp/htdocs/paperadmin/src/app/widgets/main/main.component.ts (68,5): Type '{ label: string; icon: string; color: string; onDelete: (value: any) => boolean; onUpdate: (value...' is not assignable to type 'Ng2ListViewCRUDProperty'.
  Object literal may only specify known properties, and 'color' does not exist in type 'Ng2ListViewCRUDProperty'.

ERROR in C:/xampp/htdocs/paperadmin/src/app/widgets/main/main.component.ts (68,5): Type '{ label: string; icon: string; color: string; onDelete: (value: any) => boolean; onUpdate: (value...' is not assignable to type 'Ng2ListViewCRUDProperty'.
  Object literal may only specify known properties, and 'color' does not exist in type 'Ng2ListViewCRUDProperty'.
webpack: Failed to compile.`

How can I fix this?

OS: Windows 10

**Comment by mohdrashid** [comment]
The issue was caused because, recently I updated a plug-in used in the theme. However, I forgot to reflect the change in the theme. Fixed it now, should be working.
